import Head from 'next/head'
import { FC } from 'react'
import LoginPage from '../components/users/login'
import RegisterSaleForm from '../components/sales/form'

const Home: FC = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main>
        <RegisterSaleForm/>

        <LoginPage/>
      </main>
    </div>
  )
}

export default Home
