import Head from 'next/head'
import { FC } from 'react'
import RegisterCustomerForm from '../components/customers/form'
import LoginPage from '../components/users/login'

const Home: FC = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main>
        <RegisterCustomerForm/>

        <LoginPage/>
      </main>
    </div>
  )
}

export default Home
